#################################
# PID parameters for pose seeking
#################################

# Maximum value of error integral for all PID controllers
windup_limit: 0.05

# PID gains
x_proportional_gain: 500.0
y_proportional_gain: 500.0
z_proportional_gain: 500.0
x_integral_gain: 1.0
y_integral_gain: 1.0
z_integral_gain: 1.0
x_derivative_gain: 0.1
y_derivative_gain: 0.1
z_derivative_gain: 0.1

angular_proportional_gain: 2.0
angular_integral_gain: 1.0
angular_derivative_gain: 0.1

# PID gains
# x_proportional_gain: 100
# y_proportional_gain: 100
# z_proportional_gain: 100
# x_integral_gain: 1.0
# y_integral_gain: 1.0
# z_integral_gain: 1.0
# x_derivative_gain: 0.1
# y_derivative_gain: 0.1
# z_derivative_gain: 0.1

# angular_proportional_gain: 30
# angular_integral_gain: 1.0
# angular_derivative_gain: 0.1