controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger1_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: open