joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

aubo_i5_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_joint
    - upperArm_joint
    - foreArm_joint
    - wrist1_joint
    - wrist2_joint
    - wrist3_joint
  gains:
    shoulder_joint: {p: 8000,  d: 100, i: 1, i_clamp: 1}
    upperArm_joint: {p: 14000,  d: 100, i: 1, i_clamp: 1}
    foreArm_joint: {p: 3000,  d: 20, i: 1, i_clamp: 1}
    wrist1_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    wrist2_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    wrist3_joint: {p: 100,  d: 1, i: 0, i_clamp: 1} 
  state_publish_rate: 25

pgc140_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger1_joint
  gains:
    finger1_joint: {p: 100,  i: 1, d: 1, i_clamp: 1}
  state_publish_rate: 25

gazebo_ros_control:
  pid_gains:
    # the following gains are used by the gazebo_mimic_joint plugin
    finger2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
      antiwindup: false
      publish_state: true

