joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 500

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints: &robot_joints
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    shoulder_pan_joint: { trajectory: 0.1, goal: 0.2 }
    shoulder_lift_joint: { trajectory: 0.1, goal: 0.2 }
    elbow_joint: { trajectory: 0.1, goal: 0.2 }
    wrist_1_joint: { trajectory: 0.1, goal: 0.2 }
    wrist_2_joint: { trajectory: 0.1, goal: 0.2 }
    wrist_3_joint: { trajectory: 0.1, goal: 0.2 }
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

gripper_controller:
  type: position_controllers/GripperActionController
  gains:
    finger_joint: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  joint: finger_joint
  action_monitor_rate: 20
  goal_tolerance: 0.1
  max_effort: 100
  stall_velocity_threshold: 0.05
  stall_timeout: 1.0

arm_position_controller:
  type: position_controllers/JointGroupPositionController
  joints: 
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

gazebo_ros_control:
  pid_gains:
    # shoulder_pan_joint: { p: 10000, d: 50, i: 1, i_clamp: 1 }
    # shoulder_lift_joint: { p: 12000, d: 200, i: 1, i_clamp: 1 }
    # elbow_joint: { p: 6000, d: 20, i: 1, i_clamp: 1 }
    # wrist_1_joint: { p: 1000, d: 1, i: 1, i_clamp: 1 }
    # wrist_2_joint: { p: 1000, d: 1, i: 1, i_clamp: 1 }
    # wrist_3_joint: { p: 1000, d: 1, i: 1, i_clamp: 1 }
    finger_joint: { p: 10, d: 0.1, i: 1, i_clamp: 1 }
    left_outer_finger_joint: { p: 10, d: 0.01, i: 1, i_clamp: 1 }
    # left_inner_knuckle_joint: { p: 50, d: 0.1, i: 0, i_clamp: 0 }
    left_inner_finger_joint: { p: 10, d: 0.01, i: 1, i_clamp: 1 }
    right_finger_joint: { p: 10, d: 0.1, i: 1, i_clamp: 1 }
    right_outer_finger_joint: { p: 10, d: 0.01, i: 1, i_clamp: 1 }
    # right_inner_knuckle_joint: { p: 50, d: 0.1, i: 1, i_clamp: 1 }
    right_inner_finger_joint: { p: 10, d: 0.01, i: 1, i_clamp: 1 }
