joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 200

aubo_i5_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  constraints:
      # goal_time: 0.6
      # stopped_velocity_tolerance: 0.05
      # shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      # shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      # elbow_joint: {trajectory: 0.2, goal: 0.1}
      # wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      # wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      # wrist_3_joint: {trajectory: 0.2, goal: 0.1}
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0, goal: 0}
      shoulder_lift_joint: {trajectory: 0, goal: 0}
      elbow_joint: {trajectory: 0, goal: 0}
      wrist_1_joint: {trajectory: 0, goal: 0}
      wrist_2_joint: {trajectory: 0, goal: 0}
      wrist_3_joint: {trajectory: 0, goal: 0}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 20

arm_position_controller:
  type: position_controllers/JointGroupPositionController
  joints: 
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint